defaultSemverRangePrefix: ""

nodeLinker: pnp

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  graphql-rate-limit-directive@*:
    dependencies:
      "@graphql-tools/utils": "*"
      rate-limiter-flexible: "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  "@protobufjs/inquire@*":
    dependencies:
      long: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpMode: loose

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - x64
    - arm64

yarnPath: .yarn/releases/yarn-3.2.0.cjs
