name: Continuous Integration

on:
  push:
    branches: [ main, latest ]

env:
  BUILD_MAJOR: 3
  BUILD_MINOR: 0
  BUILD_VERSION: 3.0.${{github.run_number}}

jobs:
  build-core:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: wiki-core
        tags: dev-${{env.BUILD_VERSION}}
        registry: ghcr.io
        dockerfile: dev/docker/core.dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  build-ui:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: wiki-ui
        tags: dev-${{env.BUILD_VERSION}}
        registry: ghcr.io
        dockerfile: dev/docker/ui.dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  build-combo:
    needs: [build-core, build-ui]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@0.1.4
      with:
        include: dev/combo/combo.dockerfile
        find: __BUILD_VERSION__
        replace: ${{env.BUILD_VERSION}}
    - uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: wiki-combo
        tags: dev-${{env.BUILD_VERSION}}
        registry: ghcr.io
        dockerfile: dev/combo/combo.dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  publish-beta:
    if: ${{ github.ref == 'refs/heads/latest' }}
    needs: [build-combo]
    runs-on: ubuntu-latest
    environment: beta
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull Dev Images
      run: |
        docker pull ghcr.io/requarks/wiki-core:dev-${{env.BUILD_VERSION}}
        docker pull ghcr.io/requarks/wiki-ui:dev-${{env.BUILD_VERSION}}
        docker pull ghcr.io/requarks/wiki-combo:dev-${{env.BUILD_VERSION}}
    - name: Tag Beta Images
      run: |
        docker tag ghcr.io/requarks/wiki-core:dev-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-core:beta-${{env.BUILD_VERSION}}
        docker tag ghcr.io/requarks/wiki-ui:dev-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-ui:beta-${{env.BUILD_VERSION}}
        docker tag ghcr.io/requarks/wiki-combo:dev-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-combo:beta-${{env.BUILD_VERSION}}
    - name: Push Beta Images
      run: |
        docker push ghcr.io/requarks/wiki-core:beta-${{env.BUILD_VERSION}}
        docker push ghcr.io/requarks/wiki-ui:beta-${{env.BUILD_VERSION}}
        docker push ghcr.io/requarks/wiki-combo:beta-${{env.BUILD_VERSION}}
    - name: Generate Changelog
      uses: Bullrich/generate-release-changelog@master
      id: changelog
      env:
        REPO: ${{ github.repository }}
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        body: |
          ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: true
        tag: ${{env.BUILD_VERSION}}
        token: ${{ secrets.GITHUB_TOKEN }}
  publish-release:
    if: ${{ github.ref == 'refs/heads/latest' }}
    needs: [publish-beta]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull Beta Images
      run: |
        docker pull ghcr.io/requarks/wiki-core:beta-${{env.BUILD_VERSION}}
        docker pull ghcr.io/requarks/wiki-ui:beta-${{env.BUILD_VERSION}}
        docker pull ghcr.io/requarks/wiki-combo:beta-${{env.BUILD_VERSION}}
    - name: Tag Release Images
      run: |
        docker tag ghcr.io/requarks/wiki-core:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-core:${{env.BUILD_VERSION}}
        docker tag ghcr.io/requarks/wiki-core:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-core:${{env.BUILD_MAJOR}}
        docker tag ghcr.io/requarks/wiki-core:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-core:${{env.BUILD_MAJOR}}.${{env.BUILD_MINOR}}
        docker tag ghcr.io/requarks/wiki-ui:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-ui:${{env.BUILD_VERSION}}
        docker tag ghcr.io/requarks/wiki-ui:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-ui:${{env.BUILD_MAJOR}}
        docker tag ghcr.io/requarks/wiki-ui:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-ui:${{env.BUILD_MAJOR}}.${{env.BUILD_MINOR}}
        docker tag ghcr.io/requarks/wiki-combo:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-combo:${{env.BUILD_VERSION}}
        docker tag ghcr.io/requarks/wiki-combo:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-combo:${{env.BUILD_MAJOR}}
        docker tag ghcr.io/requarks/wiki-combo:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-combo:${{env.BUILD_MAJOR}}.${{env.BUILD_MINOR}}
    - name: Push Release Images
      run: |
        docker push ghcr.io/requarks/wiki-core:${{env.BUILD_VERSION}}
        docker push ghcr.io/requarks/wiki-core:${{env.BUILD_MAJOR}}
        docker push ghcr.io/requarks/wiki-core:${{env.BUILD_MAJOR}}.${{env.BUILD_MINOR}}
        docker push ghcr.io/requarks/wiki-ui:${{env.BUILD_VERSION}}
        docker push ghcr.io/requarks/wiki-ui:${{env.BUILD_MAJOR}}
        docker push ghcr.io/requarks/wiki-ui:${{env.BUILD_MAJOR}}.${{env.BUILD_MINOR}}
        docker push ghcr.io/requarks/wiki-combo:${{env.BUILD_VERSION}}
        docker push ghcr.io/requarks/wiki-combo:${{env.BUILD_MAJOR}}
        docker push ghcr.io/requarks/wiki-combo:${{env.BUILD_MAJOR}}.${{env.BUILD_MINOR}}
    - name: Update Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        omitBody: true
        omitName: true
        replacesArtifacts: false
        draft: false
        prerelease: false
        tag: ${{env.BUILD_VERSION}}
        token: ${{ secrets.GITHUB_TOKEN }}
