name: Publish Prerelease Artifacts

on:
  push:
    tags:
      - "[0-9].*"

jobs:
  publish-beta:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get Tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Pull Dev Images
      run: |
        docker pull ghcr.io/requarks/wiki-core:dev-${{steps.tag.outputs.tag}}
        docker pull ghcr.io/requarks/wiki-ui:dev-${{steps.tag.outputs.tag}}
        docker pull ghcr.io/requarks/wiki-combo:dev-${{steps.tag.outputs.tag}}
    - name: Tag Beta Images
      run: |
        docker tag ghcr.io/requarks/wiki-core:dev-${{steps.tag.outputs.tag}} ghcr.io/requarks/wiki-core:beta-${{steps.tag.outputs.tag}}
        docker tag ghcr.io/requarks/wiki-ui:dev-${{steps.tag.outputs.tag}} ghcr.io/requarks/wiki-ui:beta-${{steps.tag.outputs.tag}}
        docker tag ghcr.io/requarks/wiki-combo:dev-${{steps.tag.outputs.tag}} ghcr.io/requarks/wiki-combo:beta-${{steps.tag.outputs.tag}}
    - name: Push Beta Images
      run: |
        docker push ghcr.io/requarks/wiki-core:beta-${{steps.tag.outputs.tag}}
        docker push ghcr.io/requarks/wiki-ui:beta-${{steps.tag.outputs.tag}}
        docker push ghcr.io/requarks/wiki-combo:beta-${{steps.tag.outputs.tag}}
    - name: Generate Changelog
      uses: Bullrich/generate-release-changelog@master
      id: changelog
      env:
        REPO: ${{ github.repository }}
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        body: |
          ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
