name: Publish Prerelease Artifacts

on:
  push:
    branches: [ latest ]

jobs:
  publish-beta:
    runs-on: ubuntu-latest
    environment: beta
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull Dev Images
      run: |
        docker pull ghcr.io/requarks/wiki-core:dev-${{github.event.release.tag_name}}
        docker pull ghcr.io/requarks/wiki-ui:dev-${{github.event.release.tag_name}}
        docker pull ghcr.io/requarks/wiki-combo:dev-${{github.event.release.tag_name}}
    - name: Tag Beta Images
      run: |
        docker tag ghcr.io/requarks/wiki-core:dev-${{github.event.release.tag_name}} ghcr.io/requarks/wiki-core:beta-${{github.event.release.tag_name}}
        docker tag ghcr.io/requarks/wiki-ui:dev-${{github.event.release.tag_name}} ghcr.io/requarks/wiki-ui:beta-${{github.event.release.tag_name}}
        docker tag ghcr.io/requarks/wiki-combo:dev-${{github.event.release.tag_name}} ghcr.io/requarks/wiki-combo:beta-${{github.event.release.tag_name}}
    - name: Push Beta Images
      run: |
        docker push ghcr.io/requarks/wiki-core:beta-${{github.event.release.tag_name}}
        docker push ghcr.io/requarks/wiki-ui:beta-${{github.event.release.tag_name}}
        docker push ghcr.io/requarks/wiki-combo:beta-${{github.event.release.tag_name}}
    - name: Generate Changelog
      uses: Bullrich/generate-release-changelog@master
      id: changelog
      env:
        REPO: ${{ github.repository }}
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        body: |
          ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
